creation_rules:
  # Flux: Kubernetes Secret manifests (encrypt stringData)
  - path_regex: (^|.*[\\/])secrets\.dev\.yaml$
    azure_keyvault: https://kv-app-openmetadata-dev.vault.azure.net/keys/openmetadata-sops-key/ecbfaaa91a814e98af94e9646be588bb
    encrypted_regex: "^(data|stringData)$"

  - path_regex: .*secrets\.test\.yaml$
    azure_keyvault: TODO
    encrypted_regex: "^(data|stringData)$"

  - path_regex: .*secrets\.prod\.yaml$
    azure_keyvault: TODO
    encrypted_regex: "^(data|stringData)$"
