apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cx-fluxed-openmetadata-encore-ns
resources:
  - ../../base
  - secrets.dev.yaml
  - ingress.yaml
patches:
  - path: helmrelease-patch.yaml
