apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
    namespace: cx-fluxed-airflow-encore-ns
type: Opaque
stringData:
    GIT_SYNC_USERNAME: ENC[AES256_GCM,data:pevNpiqd60Elsbk=,iv:OvANIP4g+29qw55bfPsU+SPuGzby3Tp/d12nI/V4XTc=,tag:y0khDgubsQnpcf4p3vm/Pw==,type:str]
    GIT_SYNC_PASSWORD: ENC[AES256_GCM,data:AHJVjdPZQwpXLcJ1zAKkOx723edMbYGgKa7DGts957to74gBVb90TA==,iv:E0fvuoGt2j3cRDDv4iImD7/T9miQvH6tNn5vklnJoLw=,tag:xlwT4jD04W20nG+WoP4vUw==,type:str]
    GITSYNC_USERNAME: ENC[AES256_GCM,data:ZQO97qThTg9KYYY=,iv:BXtFm36rACeRzF4c1IN1BLXeIciT/jCcJ+YEP7tXWx4=,tag:uLc7qpjn9mJ/QyaEUI8UGw==,type:str]
    GITSYNC_PASSWORD: ENC[AES256_GCM,data:RRHvQ5K9ykKsVmPubqkKZGNWrWGPwRH4/HR+e489TogX+0Q4O9Kb8w==,iv:bNUEQd7ioXhMH1fn7tH/VWdhZWUVgUoEkjI3KEYBdCE=,tag:PejdO6EIApbqVAf6ctDuJA==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-encore-dev-gwc-int.vault.azure.net
          name: encore-sops-key
          version: 0b82dc5fcfd1487d9903f4375cb9a83b
          created_at: "2026-02-17T10:22:33Z"
          enc: rhhAnaibShBe3TVZjNbDOZ4LGbAzbevspA2sVkf5OdVI6--KqCg_d216-b3CnBXxiO7srlQ-RK46FITaRX_sZDmOdDa-0vDghJzmJ5RLAySTuB2MYhU3Um9CZYQjMuBfcTpXg7KQwgazwXz-CYSvjLWtnOp_MPkIUM9OMseQhSvEPkbOqKwkjjMsqqhY_xDGCy2mNdvsduDTrK_0Vge7ppl6S3KpF4J14gAouuoMrauElCiU20-c_CaRTqyRgSf4Ypo5Vru9p_avg7W1OAOiyYvdozc2FapALeMX5Z-Uhii48BCRI3HAc5g4cI-0rCZtVefuSKD3h1_qFixUG1YKDA
    lastmodified: "2026-02-17T19:00:58Z"
    mac: ENC[AES256_GCM,data:VNcOKx7b6b8GD+yaBZIFRnel9Qo9ElFfTzyWovGJAKI8ocQetg3UxHQizBOY7i7GJ9jo0n+wpgrnYN2T8XnTJe8k/bdnZMXtxL8l1TRW0SG+/4WQrXZI3FiGfBuX1rKqzD38elRQ+olSc+sq5vBYmDy82/irh7cEgUrnsG9VIDM=,iv:Z0+jpjPIdrXkjN6zVjuPBK6Bg7o1NoChe/UN0Yo9AEE=,tag:vbNDekP7nQ9k2gh2EW44SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: airflow-static-jwt-secret
    namespace: cx-fluxed-airflow-encore-ns
type: Opaque
stringData:
    jwt-secret: ENC[AES256_GCM,data:GH7j97BwblraDxbC+S2F90im8b9pF5e3ByppTrRUaq+Xc7ZjpECHoTAFiiw=,iv:3HxifMadddK8rDJUIuDlAuiIuV1Ze/siC+5Gu0yd5OM=,tag:rEYNNGrDXEJ/zhS1xDzMoQ==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-encore-dev-gwc-int.vault.azure.net
          name: encore-sops-key
          version: 0b82dc5fcfd1487d9903f4375cb9a83b
          created_at: "2026-02-17T10:22:33Z"
          enc: rhhAnaibShBe3TVZjNbDOZ4LGbAzbevspA2sVkf5OdVI6--KqCg_d216-b3CnBXxiO7srlQ-RK46FITaRX_sZDmOdDa-0vDghJzmJ5RLAySTuB2MYhU3Um9CZYQjMuBfcTpXg7KQwgazwXz-CYSvjLWtnOp_MPkIUM9OMseQhSvEPkbOqKwkjjMsqqhY_xDGCy2mNdvsduDTrK_0Vge7ppl6S3KpF4J14gAouuoMrauElCiU20-c_CaRTqyRgSf4Ypo5Vru9p_avg7W1OAOiyYvdozc2FapALeMX5Z-Uhii48BCRI3HAc5g4cI-0rCZtVefuSKD3h1_qFixUG1YKDA
    lastmodified: "2026-02-17T19:00:58Z"
    mac: ENC[AES256_GCM,data:VNcOKx7b6b8GD+yaBZIFRnel9Qo9ElFfTzyWovGJAKI8ocQetg3UxHQizBOY7i7GJ9jo0n+wpgrnYN2T8XnTJe8k/bdnZMXtxL8l1TRW0SG+/4WQrXZI3FiGfBuX1rKqzD38elRQ+olSc+sq5vBYmDy82/irh7cEgUrnsG9VIDM=,iv:Z0+jpjPIdrXkjN6zVjuPBK6Bg7o1NoChe/UN0Yo9AEE=,tag:vbNDekP7nQ9k2gh2EW44SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: airflow-postgresql-secret
    namespace: cx-fluxed-airflow-encore-ns
type: Opaque
stringData:
    connection: ENC[AES256_GCM,data:KMY89OapDtOl3nWpjIv83JHlZtiWJLbKNOccnM52W0c+oOhwGYpjMILHKGu/d//PekpNN+XyQlWl/+I4XpXuybhhQ1zO+BN+Cqda6SSv8Mv9h0SnBagDJIqB6Vq+Mn5LxftecGohDRO0BIIC4lrQaEnHdlh/W731jD27tY1x6t33yhajNrLjqkmUpp2dNXOKFxTfcDxwmW77+8N/1FVb30i9zASoY33t6Fbikv/Dam8R+M7+L4Fkr47efl7eBaPnjnTBTneNTzK4tN/EB/c0Hrc06oCgQ6uoUg==,iv:DhbroBz2b+hffk9ej14Ul8DJyXLyKeK/4Sed2tQdhKo=,tag:4VLpAu6TT/ZMZaSULhBChw==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-encore-dev-gwc-int.vault.azure.net
          name: encore-sops-key
          version: 0b82dc5fcfd1487d9903f4375cb9a83b
          created_at: "2026-02-17T10:22:33Z"
          enc: rhhAnaibShBe3TVZjNbDOZ4LGbAzbevspA2sVkf5OdVI6--KqCg_d216-b3CnBXxiO7srlQ-RK46FITaRX_sZDmOdDa-0vDghJzmJ5RLAySTuB2MYhU3Um9CZYQjMuBfcTpXg7KQwgazwXz-CYSvjLWtnOp_MPkIUM9OMseQhSvEPkbOqKwkjjMsqqhY_xDGCy2mNdvsduDTrK_0Vge7ppl6S3KpF4J14gAouuoMrauElCiU20-c_CaRTqyRgSf4Ypo5Vru9p_avg7W1OAOiyYvdozc2FapALeMX5Z-Uhii48BCRI3HAc5g4cI-0rCZtVefuSKD3h1_qFixUG1YKDA
    lastmodified: "2026-02-17T19:00:58Z"
    mac: ENC[AES256_GCM,data:VNcOKx7b6b8GD+yaBZIFRnel9Qo9ElFfTzyWovGJAKI8ocQetg3UxHQizBOY7i7GJ9jo0n+wpgrnYN2T8XnTJe8k/bdnZMXtxL8l1TRW0SG+/4WQrXZI3FiGfBuX1rKqzD38elRQ+olSc+sq5vBYmDy82/irh7cEgUrnsG9VIDM=,iv:Z0+jpjPIdrXkjN6zVjuPBK6Bg7o1NoChe/UN0Yo9AEE=,tag:vbNDekP7nQ9k2gh2EW44SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
