apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: cx-fluxed-openmetadata-encore-ns
type: Opaque
stringData:
    openmetadata-postgres-username: ENC[AES256_GCM,data:MIln6H820ZfovkaAC3evNRRagDEXMYqQIwg6lMmuXuafiXzMy7Ko,iv:CCIL0rdip7CXaNUEW6WYMa746/3seDnLp1o7DYRYiQA=,tag:9ylo3LESgzZ9rq3GuZOGyg==,type:str]
    openmetadata-postgres-password: ENC[AES256_GCM,data:uVuu9NKWhJHu1v0pDjHfoD4IB2z3r1+Ymb/q/r9QXopJWi2AMJdzy9hXwZJZouDfUA==,iv:rgKCg/tN6OJS5KbYbammp+KZJ6LOORdm5qhaFa2Q3lM=,tag:2rFzwBuMmwEvKKCoIZl56g==,type:str]
    openmetadata-database-name: ENC[AES256_GCM,data:FzTle0+LNKDwkKDmpcjOxsKgUGIZ1df9JCCPayQ=,iv:veIgmDIk1Kir1jOzft+uR604LQsb2xD8S13DmBQdct8=,tag:bj2OwWA5mtbFwWStd4VApA==,type:str]
    openmetadata-database-hostname: ENC[AES256_GCM,data:gc1WYhypHSs0GTfNz0Fu6RR/6dM7C8c6KNr8HsJUjl7kDaxSWYb8Ao9wTQ==,iv:rVHCEWfLm0Dg28XJ49mOP7BUJhPIu8gAJD/EtHpgTOE=,tag:0fyC/esjiadKRFXuONpY5A==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-app-openmetadata-dev.vault.azure.net
          name: openmetadata-sops-key
          version: ecbfaaa91a814e98af94e9646be588bb
          created_at: "2026-03-16T12:54:30Z"
          enc: s_JHMtCYAC8lbEtvWTic_ZBpYhCsloz5-9UvzRi4kP9eB1criJGFufhr2wgQ0SmXB1zw706TtYat_wRvHE2La00nMz_Syl7zYrsV-XxtrId8VVt4b2sl9NEVlJqoFoOgdvinDEiPV1_RbLSABPWByrjOG8SwLE-MUnO-kce9j-WPyMBSzzFHkUv2bd6CIKi6vdUbubjl-nbLnFslYa3HpTC0dyrxwHZaD4QTgqSMLXyLENJXxwIh711NX9nRs_rc2fmZeSvaIjtU0z6jWUT-TYKxY_YCvGxGqLAnMW9T-HN2-HqPX_HVElfO0b_gN-_jOA9SkVtMRectA6syofyVAQ
    lastmodified: "2026-03-16T12:56:45Z"
    mac: ENC[AES256_GCM,data:Z3M/EHL4g0iHvEhWkeJdaXtKkO6GuXQ6OTaY7f++Gk0ACTGV0j01AEoIp+iN/uitUQI1ElPiY8Y/E0SMiB1hAOmIG1UNDbPK+7sag4aCJy3g0ziqQ0VIyozEllPEDhV7QI+rSo1UteAKBm4Fv2d8swOlddRjUQtTr//bgF2ILB8=,iv:Kn9e+q90wKJiZ4q7pvLqBSqzqLtJJGFxawAyDw3MKlA=,tag:sj+cbnbuLrXCly6G7qHPDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: airflow-secrets
    namespace: cx-fluxed-openmetadata-encore-ns
type: Opaque
stringData:
    openmetadata-airflow-password: ENC[AES256_GCM,data:MfaxO24iJfO4jxsGfwBS,iv:b7nLcCG38V9EiKBo6GVl+3xdq+2bNod14VQDhIVG2TQ=,tag:nwJwcedTju1Z2uF6/y4ThA==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-app-openmetadata-dev.vault.azure.net
          name: openmetadata-sops-key
          version: ecbfaaa91a814e98af94e9646be588bb
          created_at: "2026-03-16T12:54:30Z"
          enc: s_JHMtCYAC8lbEtvWTic_ZBpYhCsloz5-9UvzRi4kP9eB1criJGFufhr2wgQ0SmXB1zw706TtYat_wRvHE2La00nMz_Syl7zYrsV-XxtrId8VVt4b2sl9NEVlJqoFoOgdvinDEiPV1_RbLSABPWByrjOG8SwLE-MUnO-kce9j-WPyMBSzzFHkUv2bd6CIKi6vdUbubjl-nbLnFslYa3HpTC0dyrxwHZaD4QTgqSMLXyLENJXxwIh711NX9nRs_rc2fmZeSvaIjtU0z6jWUT-TYKxY_YCvGxGqLAnMW9T-HN2-HqPX_HVElfO0b_gN-_jOA9SkVtMRectA6syofyVAQ
    lastmodified: "2026-03-16T12:56:45Z"
    mac: ENC[AES256_GCM,data:Z3M/EHL4g0iHvEhWkeJdaXtKkO6GuXQ6OTaY7f++Gk0ACTGV0j01AEoIp+iN/uitUQI1ElPiY8Y/E0SMiB1hAOmIG1UNDbPK+7sag4aCJy3g0ziqQ0VIyozEllPEDhV7QI+rSo1UteAKBm4Fv2d8swOlddRjUQtTr//bgF2ILB8=,iv:Kn9e+q90wKJiZ4q7pvLqBSqzqLtJJGFxawAyDw3MKlA=,tag:sj+cbnbuLrXCly6G7qHPDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: opensearch-admin-password
    namespace: cx-fluxed-openmetadata-encore-ns
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:PQuc7BDFsngACIuQ,iv:zF2rpcYmCymgglb1fksYUQwHdIVlpY0SII4iHPpAYTc=,tag:XGRfuS96shgGG00vRVuLaA==,type:str]
sops:
    azure_kv:
        - vault_url: https://kv-app-openmetadata-dev.vault.azure.net
          name: openmetadata-sops-key
          version: ecbfaaa91a814e98af94e9646be588bb
          created_at: "2026-03-16T12:54:30Z"
          enc: s_JHMtCYAC8lbEtvWTic_ZBpYhCsloz5-9UvzRi4kP9eB1criJGFufhr2wgQ0SmXB1zw706TtYat_wRvHE2La00nMz_Syl7zYrsV-XxtrId8VVt4b2sl9NEVlJqoFoOgdvinDEiPV1_RbLSABPWByrjOG8SwLE-MUnO-kce9j-WPyMBSzzFHkUv2bd6CIKi6vdUbubjl-nbLnFslYa3HpTC0dyrxwHZaD4QTgqSMLXyLENJXxwIh711NX9nRs_rc2fmZeSvaIjtU0z6jWUT-TYKxY_YCvGxGqLAnMW9T-HN2-HqPX_HVElfO0b_gN-_jOA9SkVtMRectA6syofyVAQ
    lastmodified: "2026-03-16T12:56:45Z"
    mac: ENC[AES256_GCM,data:Z3M/EHL4g0iHvEhWkeJdaXtKkO6GuXQ6OTaY7f++Gk0ACTGV0j01AEoIp+iN/uitUQI1ElPiY8Y/E0SMiB1hAOmIG1UNDbPK+7sag4aCJy3g0ziqQ0VIyozEllPEDhV7QI+rSo1UteAKBm4Fv2d8swOlddRjUQtTr//bgF2ILB8=,iv:Kn9e+q90wKJiZ4q7pvLqBSqzqLtJJGFxawAyDw3MKlA=,tag:sj+cbnbuLrXCly6G7qHPDw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
