apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openmetadata-ingestion
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openmetadata-ingestion
subjects:
  - kind: ServiceAccount
    name: openmetadata
    namespace: cx-fluxed-openmetadata-encore-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openmetadata-ingestion
